### PR TITLE
Bug/iii 3673 redirect to dashboard when a path is invalid in angular app

### PR DESCRIPTION
**Pull request by simon-debruijn**
### Added

- Redirect to dashboard when a path is invalid in angular app

related PR: [PR 155](https://github.com/cultuurnet/udb3-frontend/pull/155)

---

Ticket: https://jira.uitdatabank.be/browse/III-3673

### CODE REVIEW

**Review by geoffreydhuyvetters — APPROVED** [review]

**Review by bertramakers — APPROVED** [review]

**Comment by simon-debruijn** [comment]
> Code looks good to me! Just wondering what we're going to do with that message in the React app. The PR states:
> 
> > redirect to dashboard when a path is invalid in angular app
> 
> However shouldn't we show a 404 Not Found page instead then (in the React app)?
> 
> Edit: Ah I see it's already implemented in React as a redirect to `/dashboard`: https://github.com/cultuurnet/udb3-frontend/pull/155/files#diff-7ed85bcba7790b36407e1a6dda8c455dcef4aae62ebe666a363fc582308e1120R87
> 
> My assumption would be that if the page does not exist in React, we try to show it in the Angular app, and if it doesn't exist there it's a 404?

Yes this also seems like a logical result, the 404 page.

@geoffreydhuyvetters should we change it?

**Comment by geoffreydhuyvetters** [comment]
We don't have a proper 404 page now, but I guess we could create one

**Comment by bertramakers** [comment]
> We don't have a proper 404 page now, but I guess we could create one

The AngularJS didn't either, so I guess technically that would be a new feature 😂 
Can we create a really simple one in the React app and if needed polish it later?
If it just says "page not found" or something similar I think it's good enough for now. It would be better than what we had before anyway.

**Comment by bertramakers** [comment]
Proof that we the AngularJS app doesn't have one either.

Screen Shot 2021-01-05 at 17 30 45

**Comment by simon-debruijn** [comment]
> > We don't have a proper 404 page now, but I guess we could create one
> 
> The AngularJS didn't either, so I guess technically that would be a new feature 😂
> Can we create a really simple one in the React app and if needed polish it later?
> If it just says "page not found" or something similar I think it's good enough for now. It would be better than what we had before anyway.

Yep already on it! 😄

**Pull request merged**
