### PR TITLE
III-4922 - Add styling to round components in the angular app

### PR DESCRIPTION
**Pull request by simon-debruijn**
### Added

-  Rounded corners

---

Ticket: https://jira.uitdatabank.be/browse/III-4922

### CODE REVIEW

**Comment by brampauwelyn** [comment]
On some places the contrast may not be sufficient for the users:

- Datepicker button
- Contrast between past dates & future dates is not clear

Screenshot 2022-10-11 at 09 24 31

**Review by brampauwelyn — CHANGES_REQUESTED** [review]
Good result with minimal styling 👍

**Comment by simon-debruijn** [comment]
> On some places the contrast may not be sufficient for the users:
> 
> * Datepicker button
> * Contrast between past dates & future dates is not clear
> 
> Screenshot 2022-10-11 at 09 24 31
Screenshot 2022-10-11 at 16 44 16

New design

**Comment by brampauwelyn** [comment]
> > On some places the contrast may not be sufficient for the users:
> > 
> > * Datepicker button
> > * Contrast between past dates & future dates is not clear
> > 
> > Screenshot 2022-10-11 at 09 24 31
> 
> Screenshot 2022-10-11 at 16 44 16
> 
> New design

Looks better!
However the past dates still looks like a button, maybe remove the box-shadow on past dates as well?

**Review by brampauwelyn — APPROVED** [review]

**Pull request merged**
