### PR TITLE
OPS-54 add maintenance option to udb repo

### PR DESCRIPTION
**Pull request by stijnswaanen**

### CODE REVIEW

**Comment by bertramakers** [comment]
I like the approach with the `.htaccess` condition that checks if `maintenance.enable` is present, but should this really be a part of the (front-end) app itself? Wouldn't it be easier and better if the maintenance page would live in a separate repo and be re-usable across applications? The `.htaccess` check could probably be configured for all/multiple applications on the server level. What is your opinion @willaerk ?

**Comment by bertramakers** [comment]
Also, why do we need a `maintenance.disable`? The documentation mentions:

> rename maintenance.disable to maintenance.enable
> `mv maintenance.disable maintenance.enable`

But you could just as well do:

> `touch maintenance.enable`

And revert it using:

> `rm maintenance.enable`

It's not that the presence of `maitenance.disable` makes it completely clear how to enable it, because my first guess for example would be that _removing_ `maitenance.disable` would enable maintenance mode.

**Comment by brampauwelyn** [comment]
> Wouldn't it be easier and better if the maintenance page would live in a separate repo and be re-usable across applications?

It seems like a good idea to keep it in a seperate repo, we could use it for omd (open monumenten dag) and the nl version of the udb3-angular app.

**Comment by bertramakers** [comment]
Closing because we're going with the other approach.

**Pull request closed without merging**
